language: ruby
rvm:
  - 1.9.2
  - 1.9.3
before_install:
 - sudo apt-get install build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev ruby-dev
